#!/usr/bin/env python3
"""Persist bypass excludes into Hiddify-native routing prefs.

Hiddify rebuilds current-config.json on Connect. Durable sources are:

* shared_preferences.json — direct-dns-address, bypass-lan, enable-dns-routing
* route_rule.proto — domain/IP rules with outbound=direct (baseDir)

Live JSON patches alone are wiped on reconnect.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Iterable, Optional

from hiddify_bypass import (
    BypassSpec,
    classify_dns_pattern,
    discover_direct_dns,
    spec_with_direct_dns,
)

# Generated by: protoc -I=proto --python_out=proto proto/route_rule.proto
_PROTO_DIR = Path(__file__).resolve().parent / "proto"
if str(_PROTO_DIR) not in sys.path:
    sys.path.insert(0, str(_PROTO_DIR))

import route_rule_pb2 as rr  # noqa: E402

MANAGED_PREFIX = "hiddify-cursor-"
DNS_RULE_NAME = f"{MANAGED_PREFIX}dns"
IP_RULE_NAME = f"{MANAGED_PREFIX}ip"


def route_rule_path_candidates() -> list[Path]:
    homes = ["/root", os.path.expanduser("~")]
    packages = ("app.hiddify.com", "hiddify")
    out: list[Path] = []
    seen: set[str] = set()
    for home in homes:
        for package in packages:
            path = Path(home) / ".local" / "share" / package / "route_rule.proto"
            key = str(path)
            if key not in seen:
                out.append(path)
                seen.add(key)
    return out


def bypass_prefs_overlay(spec: BypassSpec, lan_dns: Optional[Iterable[str]] = None) -> dict:
    """Prefs Hiddify reads when regenerating core config."""
    servers = list(lan_dns) if lan_dns is not None else discover_direct_dns()
    overlay: dict = {
        "flutter.bypass-lan": True,
        # Region ir already sends .ir / geosite-ir to dns-direct; point that
        # resolver at office DNS so split-horizon names resolve.
        "flutter.enable-dns-routing": True,
    }
    if servers:
        overlay["flutter.direct-dns-address"] = servers[0]
    return overlay


def build_route_rule(spec: BypassSpec, lan_dns: Optional[Iterable[str]] = None) -> rr.RouteRule:
    """Build RouteRule protobuf for domain/IP DIRECT excludes."""
    full = spec_with_direct_dns(spec, lan_dns if lan_dns is not None else discover_direct_dns())
    suffixes: list[str] = []
    keywords: list[str] = []
    regexes: list[str] = []
    for pattern in full.dns:
        kind, value = classify_dns_pattern(pattern)
        if kind == "suffix":
            suffixes.append(value)
        elif kind == "keyword":
            keywords.append(value)
        elif kind == "regex":
            regexes.append(value)

    out = rr.RouteRule()
    order = 0
    if suffixes or keywords or regexes:
        rule = out.rules.add()
        rule.list_order = order
        rule.enabled = True
        rule.name = DNS_RULE_NAME
        rule.outbound = rr.direct
        rule.domain_suffixes.extend(suffixes)
        rule.domain_keywords.extend(keywords)
        rule.domain_regexes.extend(regexes)
        order += 1
    if full.ips:
        rule = out.rules.add()
        rule.list_order = order
        rule.enabled = True
        rule.name = IP_RULE_NAME
        rule.outbound = rr.direct
        rule.ip_cidrs.extend(full.ips)
    return out


def _merge_managed(existing: rr.RouteRule, managed: rr.RouteRule) -> rr.RouteRule:
    kept = [r for r in existing.rules if not str(r.name).startswith(MANAGED_PREFIX)]
    merged = rr.RouteRule()
    for i, rule in enumerate([*kept, *managed.rules]):
        item = merged.rules.add()
        item.CopyFrom(rule)
        item.list_order = i
    return merged


def write_route_rule_file(path: Path, spec: BypassSpec, lan_dns: Optional[Iterable[str]] = None) -> bool:
    """Write/merge managed rules into route_rule.proto. Returns True if changed."""
    managed = build_route_rule(spec, lan_dns)
    existing = rr.RouteRule()
    if path.is_file():
        existing.ParseFromString(path.read_bytes())
    merged = _merge_managed(existing, managed)
    payload = merged.SerializeToString()
    previous = path.read_bytes() if path.is_file() else b""
    if previous == payload:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(payload)
    return True
