# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_rule.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10route_rule.proto\x12\x06\x63onfig\"/\n\tRouteRule\x12\"\n\x05rules\x18\x01 \x03(\x0b\x32\x0c.config.RuleR\x05rules\"\x8c\x05\n\x04Rule\x12\x1e\n\nlist_order\x18\x01 \x01(\rR\nlist_order\x12\x18\n\x07\x65nabled\x18\x02 \x01(\x08R\x07\x65nabled\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12,\n\x08outbound\x18\x04 \x01(\x0e\x32\x10.config.OutboundR\x08outbound\x12\x1b\n\trule_sets\x18\x05 \x03(\tR\x08rule_set\x12#\n\rpackage_names\x18\x06 \x03(\tR\x0cpackage_name\x12#\n\rprocess_names\x18\x07 \x03(\tR\x0cprocess_name\x12#\n\rprocess_paths\x18\x08 \x03(\tR\x0cprocess_path\x12)\n\x07network\x18\t \x01(\x0e\x32\x0f.config.NetworkR\x07network\x12\x1f\n\x0bport_ranges\x18\n \x03(\tR\nport_range\x12-\n\x12source_port_ranges\x18\x0b \x03(\tR\x11source_port_range\x12-\n\tprotocols\x18\x0c \x03(\x0e\x32\x10.config.ProtocolR\x08protocol\x12\x19\n\x08ip_cidrs\x18\r \x03(\tR\x07ip_cidr\x12\'\n\x0fsource_ip_cidrs\x18\x0e \x03(\tR\x0esource_ip_cidr\x12\x17\n\x07\x64omains\x18\x0f \x03(\tR\x06\x64omain\x12&\n\x0f\x64omain_suffixes\x18\x10 \x03(\tR\rdomain_suffix\x12\'\n\x0f\x64omain_keywords\x18\x11 \x03(\tR\x0e\x64omain_keyword\x12$\n\x0e\x64omain_regexes\x18\x12 \x03(\tR\x0c\x64omain_regex*F\n\x08Outbound\x12\t\n\x05proxy\x10\x00\x12\n\n\x06\x64irect\x10\x01\x12\x18\n\x14\x64irect_with_fragment\x10\x02\x12\t\n\x05\x62lock\x10\x03*$\n\x07Network\x12\x07\n\x03\x61ll\x10\x00\x12\x07\n\x03tcp\x10\x01\x12\x07\n\x03udp\x10\x02*J\n\x08Protocol\x12\x07\n\x03tls\x10\x00\x12\x08\n\x04http\x10\x01\x12\x08\n\x04quic\x10\x02\x12\x08\n\x04stun\x10\x03\x12\x07\n\x03\x64ns\x10\x04\x12\x0e\n\nbittorrent\x10\x05\x42K\n\x1e\x63om.hiddify.core.api.v2.configZ)github.com/hiddify/hiddify-core/v2/configb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_rule_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.hiddify.core.api.v2.configZ)github.com/hiddify/hiddify-core/v2/config'
  _OUTBOUND._serialized_start=732
  _OUTBOUND._serialized_end=802
  _NETWORK._serialized_start=804
  _NETWORK._serialized_end=840
  _PROTOCOL._serialized_start=842
  _PROTOCOL._serialized_end=916
  _ROUTERULE._serialized_start=28
  _ROUTERULE._serialized_end=75
  _RULE._serialized_start=78
  _RULE._serialized_end=730
# @@protoc_insertion_point(module_scope)
